services:
  lnd-backup:
    build: .
    container_name: lnd-backup-monitor
    restart: unless-stopped
    
    environment:
      # Required - Storage connection string from .env file
      - STORAGE_CONNECTION_STRING=${STORAGE_CONNECTION_STRING}
      
      # Network configuration - using signet for Mutinynet
      - NETWORK=signet
      
      # Paths
      - LND_DATA_DIR=/lnd
      - LND_CHANNEL_BACKUP_PATH=/lnd/data/chain/bitcoin/${NETWORK:-signet}/channel.backup
      - TAPD_DATA_DIR=/tapd
      
      # Backup settings
      - CHECK_INTERVAL=${CHECK_INTERVAL:-300}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - ENABLE_TAPD=${ENABLE_TAPD:-false}
      - BACKUP_DIR=${BACKUP_DIR:-/lightning-backups}
      - LOCAL_BACKUP_DIR=${LOCAL_BACKUP_DIR:-/var/backup/lnd}
      - KEEP_LAST_N_BACKUPS=${KEEP_LAST_N_BACKUPS:-30}
      
      # System identifier - use host hostname instead of container hostname
      - SYSTEM_ID=${SYSTEM_ID:-${HOSTNAME}}
    
    volumes:
      # Mount LND data directory (read-only) - using actual path
      - "/home/ubuntu/volumes/.lnd:/lnd:ro"
      
      # Local backup directory (maps to host system)
      - "${LOCAL_BACKUP_DIR:-./local-backups}:/var/backup/lnd"
      
      # Optional: TAP daemon data
      - "${TAPD_DATA_DIR:-./tapd-data}:/tapd:ro"
    
    # Healthcheck
    healthcheck:
      test: ["CMD", "pgrep", "-f", "lnd-backup-monitor"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Security
    user: "1000:1000"
    # read_only: true  # Disabled to allow config file writes
    tmpfs:
      - /tmp
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.2'
        reservations:
          memory: 64M
          cpus: '0.1'

  # Example: Full LND + backup stack
  # Uncomment if you want to run LND alongside the backup
  # lnd:
  #   image: lightninglabs/lnd:latest
  #   container_name: lnd
  #   volumes:
  #     - lnd-data:/home/lnd/.lnd
  #     - ./lnd.conf:/home/lnd/.lnd/lnd.conf:ro
  #   ports:
  #     - "9735:9735"
  #     - "10009:10009"
  #   depends_on:
  #     - bitcoind
  #   restart: unless-stopped

  # bitcoind:
  #   image: ruimarinho/bitcoin-core:latest
  #   container_name: bitcoind
  #   volumes:
  #     - bitcoin-data:/home/bitcoin/.bitcoin
  #     - ./bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf:ro
  #   ports:
  #     - "8332:8332"
  #   restart: unless-stopped

# volumes:
#   lnd-data:
#   bitcoin-data: